services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=kate'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=kate'
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}